[network]
enable_proxy = true
proxy_host = "localhost:1080"

# request header
[useragent]
default = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36"
eudic = "/eusoft_eudic_en_win32/13.0.0/E1642045/"

# detect the new version of the regular set
[regx]
4kvideodownloader = "(?<=videodownloader_)[0-9.]+(?=_windows_x64)"
115 = '(?<=115pc_)[0-9.]+(?=\.exe)'
adrive = "(?<=aliyun-drive-desktop-version/)[0-9.]+"
aida64 = '(?<=version">)[0-9.]+(?=</td>)'
bypass = '[0-9.]+(?=.zip)'
ccleaner = '(?<=CCleaner v)[0-9.]+'
centbrowser = '(?<=Version: )[0-9.]+'
chfs = '(?<=chfs-windows-x64-)[0-9.]+(?=\.zip)'
chrome = '(?<=版本：)[0-9.]+'
clash-for-windows = '(?<=v )[0-9.]+'
claunch = '(?<=CLaunch 64-bit Unicode Ver. )[0-9.]+'
contextmenumanager = '(?<=releases/tag/)v?[0-9.]+'
coodesker = '(?<=releases/tag/)v?[0-9.]+'
cosbrowser = '[0-9.]+(?=.exe)'
dismpp = '(?<=releases/tag/)v?[0-9.]+'
ditto = '(?<=versionDots=")[0-9.]+'
emeditor = '(?<=Download latest version: v)[0-9.]+'
es = '(?<=href="/ES-)[0-9.]+(?=\.zip")'
eudic = '(?<="version":")[0-9.]+'
fastcopy = '(?<=FastCopy ver )[0-9.]+'
fscapture = '(?<=Version\s+)[0-9.]+'
fsresizer = '(?<=Version\s+)[0-9.]+'
gost = '(?<=releases/tag/)v?[0-9.]+'
hbuilderx = "(?<=\"version\":\\s+\")[0-9.]+"
iobitdriverbooster = '(?<=<span>V\s+)[0-9.]+'
iobituninstaller = '(?<=<span>V\s+)[0-9.]+'
kodobrowser = '(?<=kodo-browser-Windows-x64-v)[0-9.]+(?=.zip)'
kodoimport = '(?<=kodoimport_windowsOS_64_v)[0-9.]+(?=.tar.gz)'
lightproxy = '(?<=releases/tag/)v?[0-9.]+'
mouseinc = '(?<=版本：)[0-9.]+'
n-m3u8dl-cli = '(?<=N_m3u8DL-CLI_v)[0-9r.]+'
neatreader = '(?<=最新版本：)[0-9.]+'
neteasemusic = '[0-9.]+(?=.exe)'
newfiletime = '(?<=NewFileTime\s+)[0-9.]+'
notepad2 = '(?<=releases/tag/)v?[0-9r.]+'
notepad3 = '(?<=releases/tag/RELEASE_)[0-9.]+'
ocam = '(?<=oCam_v)[0-9.]+(?=.exe)'
oss-browser = '(?<=oss-browser/)[0-9.]+(?=/oss-browser-win32-x64.zip)'
ossutil = '(?<=ossutil/)[0-9.]+(?=/ossutil64.zip)'
pdf-xchange-editor-plus = '(?<="versionname"><strong>)[0-9.]+'
pdfpatcher = '(?<=下载：?.+版\s*)[0-9.]+'
picgo = '(?<=tree/v)[0-9.]+(?=")'
protoc = '(?<=Protocol Buffers v)[0-9.]+'
proxifier = '(?<=Version: )[0-9.]+'
q-dir = '(?<=New in version )[0-9.]+'
qshell = '(?<=qshell-v)[0-9.]+(?=-windows-amd64)'
remnote = '[0-9.]+(?=-Setup.exe)'
renamer = '(?<=/download/renamer/installer/)[0-9.]+'
sandboxie-plus = '(?<=releases/tag/)v?[0-9.]+'
shadowsocksrr = '(?<=releases/tag/)v?[0-9.]+'
skylark = '(?<=/skylark_x64-v)[0-9.]+(?=\.7z)'
stellarplayer = '(?<=version = )[0-9.]+'
tencentmeeting = '(?<="version":")[0-9.]+(?=")'
totalcommander = '(?<=Version\s+)[0-9.]+(?=,)'
ultraiso = '(?<=UltraISO\s+)[0-9.]+(?=\s+released)'
uninstalltool = '(?<=release-notes">)[0-9.]+'
v2rayn = '(?<=releases/tag/)[0-9.]+'
wechat = '(?<=WeChatSetup(_|-))[0-9.]+(?=\.exe)'
wesing = "(?<=version_pc:\\')[0-9.]+"
wisecare365 = '(?<=当前版本: )[0-9.]+'
xiaoji = '(?<=xiaoji_)[0-9.]+(?=\.exe)'
xyplorer = '(?<=class="smaller">)[0-9.]+'
zhumu = '(?<=latest-pbt/)[0-9.]+'

# block apps that do not need to be updated or cannot be updated
[shieldapp]
2345pic = true
acmekit = true
baidunetdisk = true
bandicam = true
beyondcompare = true
chrome = true
ecloud = true
edge = true
exescope = true
foobar2000 = true
goodsync = true
hdtune = true
idm = true
iqiyi = true
kbootopt = true
kcleaner = true
kodoimport = true
ksoftmgr = true
ludashi = true
mouseinc = true
notepad2-mod = true
pdfshaper = true
potplayer = true
qq = true
qqlive = true
ting = true
typeeasy = true
wechat = true
xiaowan = true
xiuxiu = true
xtools = true
zhumu = true

# match the new version via URL redirection
[redirecturl]
bypass = "https://www.bypass.cn/api/download?name=Bypass.zip"
cosbrowser = "https://cos5.cloud.tencent.com/cosbrowser/cosbrowser-setup-latest.exe"
neteasemusic = "https://music.163.com/api/pc/package/download/latest"
remnote = "https://www.remnote.io/desktop/windows"
zhumu = "https://url.zhumu.me/783e"

# replace App's Homepage、URL
[replaceurl]
4kvideodownloader = "https://www.4kdownload.com/downloads/12"
115 = "https://appversion.115.com/1/web/1.0/api/chrome"
adrive = "https://www.aliyundrive.com/desktop/version/update.json"
aida64 = "https://www.aida64.com/downloads"
ccleaner = "https://www.ccleaner.com/ccleaner/download"
dismpp = "https://github.com/Chuyu-Team/Dism-Multi-language"
eudic = "http://api.frdic.com/api/v2/appsupport/checkversion"
hbuilderx = "https://download1.dcloud.net.cn/hbuilderx/release.json"
idm = "https://www.lanzoux.com/b0i6zkze"
kodobrowser = "https://developer.qiniu.com/kodo/tools/5972/kodo-browser"
neatreader = "https://www.neat-reader.cn/downloads/windows"
ocam = "https://ohsoft.net/update/download.php"
oss-browser = "https://help.aliyun.com/document_detail/209974.html"
ossutil = "https://help.aliyun.com/document_detail/120075.html"
pdf-xchange-editor-plus = "https://www.tracker-software.com/product/downloads"
pdfpatcher = "https://www.cnblogs.com/pdfpatcher/archive/2011/02/25/Index.html"
picgo = "https://github.com/Molunerfinn/PicGo/releases"
renamer = "https://www.den4b.com/downloads/renamer"
skylark = "https://api.github.com/repos/adonais/skylark/releases/latest"
stellarplayer = "https://player-update.coldlake1.com/version/updater/stable_x64.ini"
tencentmeeting = "https://meeting.tencent.com/web-service/query-download-info?q=%5B%7B%22package-type%22%3A%22app%22%2C%22channel%22%3A%220300000000%22%2C%22platform%22%3A%22windows%22%7D%5D&nonce=1234567890abcdef"
uninstalltool = "https://crystalidea.com/uninstall-tool/download"
wesing = "https://kg.qq.com/gtimg/mediastyle/musiccm/kg/kg_feature.js"